### ISSUE TITLE
Drop unlit torch as stick

### ISSUE THREAD

**Issue by tacotexmex** [tenplus1/real_torch#2]
Since a torch = stick + coal, why not turn extinguished torches back into sticks? It reduces the number of items that one need to host in inventory and seems more logical to me.

**Comment by tacotexmex** [comment]
How stupid of me, didn't realize that. How about a "4 extinguished torches  = 1 stick" recipe?

**Comment by tenplus1** [comment]
That would be going backwards in the crafting chain, but... I will make them burnable in furnaces as fuel :)

**Comment by tenplus1** [comment]
1 extinguished torch + 1 coal dust = 1 torch... they can be recycled :)

**Comment by tacotexmex** [comment]
Fair enough! Thank you for your time :slightly_smiling_face:
